### ISSUE TITLE
bc should probably be listed as a dependency

### ISSUE THREAD

**Issue by MisterChief53** [mslcarlson/zathura-pywal#1]
bc is used in the script, but it is not installed in arch by default, and many other minimal distros. Users should be made aware of that.

**Comment by matthewlscarlson** [comment]
Ah, I didn't know that bc wasn't a system default.

I just took a look at the script and ended up removing bc from it altogether. I was using bc to convert hex to RGB, but as it turns out, this can be achieved in a much simpler manner: 

printf '%d' 0x${foo}

Don't know why I was using bc in the first place.
